name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build & Test (CMake)
    runs-on: ubuntu-latest
    env:
      CC: gcc-14
      CXX: g++-14
      CFLAGS: --coverage
      CXXFLAGS: --coverage

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install GTest
        run: sudo apt-get install -y libgtest-dev

      - name: Dashboard Build
        uses: chorse-dev/cmake-action@master
        with:
          build-name: Linux GCC
          change-id: ${{ github.sha }}
          cmake-generator: Ninja
          coverage-command: gcov-14
          use-launchers: ON
